#端口为8084的一个服务中心
server:
  port: 8084
eureka:
  instance:
    hostname: Eureka_8084_eureka_instance_hostname
  client:
    register-with-eureka: false #服务注册 false 自己不注册到服务中心
    fetchRegistry: false   #服务发现  表示自己端就是注册中心 我的职责就是维护服务实例 false  自己不获取注册信息
    service-url:    #集群的情况下，服务端之间要互相注册，指向对方
      defaultZone: http://eureka8083.com:8083
#      defaultZone: http://${com.tyl.server8083.httpName}:${com.tyl.server8083.serverPort}/eureka/
#看别人说，如果要配置三个以上，只需要弄成回字型即可