server:
  port: 80
#spring:
#  redis:
#    host: 127.0.0.1
#    password:
#    port: 6379
eureka:
  client:
    fetch-registry: false #不向eureka注册自己
    register-with-eureka: false #服务注册 false 自己不注册到服务中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: localhost_port_80
    appname: springcloud-dept-80_appname
info:
  name: localhost_port_80_infoName

