server:
  port: 8081
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    client-name: "App_8081"
  cache:
    redis:
      time-to-live: 10
  application:
    name: provider
eureka:
  client:
    fetch-registry: true #服务发现  表示自己端不是注册中心 true  自己获取注册信息
    register-with-eureka: true #服务注册 true 自己注册到服务中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka, #只能通过这个Map方法注册这个firstZone来设置地址，可以通过，增加
  instance:
    instance-id: springcould-dept-8081-tyl-instance-id
    appname: provider
info:
  company: com.tyl
  applicationName: springcloud_dept_8081_tyl

